from collections import defaultdict
from gtnlplib import constants

theta_hand_original = defaultdict(float,
                         {('worldnews','worldnews'):1.,
                          ('worldnews','news'):.5,
                          ('worldnews','world'):.5,
                          ('science','science'):1.,
                          ('askreddit','askreddit'):1.,
                          ('askreddit','ask'):0.5,
                          ('iama','iama'):1,
                          ('todayilearned','til'):1.,
                          ('todayilearned','todayilearned'):1.,
                          ('iama',constants.OFFSET):0.1
                         })

# add some more weights to this for deliverable 2.3
theta_hand = defaultdict(float,
                 {('worldnews','worldnews'):1.,
                  ('worldnews','news'):1.,
                  ('worldnews','world'):.7,
                  ('worldnews','to'):.8,
                  ('worldnews','the'):.7,
                  ('science','science'):1.,
                  ('science','a'):.8,
                  ('science','is'):.5,
                  ('science','not'):.5,
                  ('science','plant'):1.,
                  ('askreddit','askreddit'):1.,
                  ('askreddit','ask'):0.8,
                  ('askreddit','reddit'):1.,
                  ('askreddit','*'):1.,
                  ('iama','iama'):1.,
                  ('iama','i'):1.,
                  ('iama','of'):.8,
                  ('iama','a'):1.,
                  ('iama','you'):1.,
                  ('iama','for'):1.,
                  ('iama','did'):.5,
                  ('todayilearned','todayilearned'):1.,
                  ('todayilearned','learned'):1.,
                  ('todayilearned','today'):.5,
                  ('todayilearned','i'):.7,
                  ('todayilearned','fuck'):.7,
                  ('todayilearned','porn'):.5,
                  ('iama',constants.OFFSET):0.5,
                  ('worldnews',constants.OFFSET):0.22,
                  ('science',constants.OFFSET):0.22,
                  ('askreddit',constants.OFFSET):0.13,
                  ('todayileanred',constants.OFFSET):0.09,
                 })